// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcX5hlpyZ_uxrIRJ5BGDrrT237ErtLVJY',
    appId: '1:988180918044:web:17feac5d57422f0b1794d9',
    messagingSenderId: '988180918044',
    projectId: 'bizfuel-ecf95',
    authDomain: 'bizfuel-ecf95.firebaseapp.com',
    storageBucket: 'bizfuel-ecf95.appspot.com',
    measurementId: 'G-FP3491R0Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQLDReTagXny3xO4BLhX7Poxan6qGwMlI',
    appId: '1:988180918044:android:1b35e3d8dfae3d671794d9',
    messagingSenderId: '988180918044',
    projectId: 'bizfuel-ecf95',
    storageBucket: 'bizfuel-ecf95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIPiTr7WOu35icKZBr149DDD-qfJ5xqg',
    appId: '1:988180918044:ios:cdf924d267c911211794d9',
    messagingSenderId: '988180918044',
    projectId: 'bizfuel-ecf95',
    storageBucket: 'bizfuel-ecf95.appspot.com',
    iosBundleId: 'com.example.bizfuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIPiTr7WOu35icKZBr149DDD-qfJ5xqg',
    appId: '1:988180918044:ios:cdf924d267c911211794d9',
    messagingSenderId: '988180918044',
    projectId: 'bizfuel-ecf95',
    storageBucket: 'bizfuel-ecf95.appspot.com',
    iosBundleId: 'com.example.bizfuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcX5hlpyZ_uxrIRJ5BGDrrT237ErtLVJY',
    appId: '1:988180918044:web:1723e472995ce9f01794d9',
    messagingSenderId: '988180918044',
    projectId: 'bizfuel-ecf95',
    authDomain: 'bizfuel-ecf95.firebaseapp.com',
    storageBucket: 'bizfuel-ecf95.appspot.com',
    measurementId: 'G-JVW6N8LXVW',
  );
}
